
/**
 * @fileOverview A collection of Hadith related to charity.
 */
import type { Quote } from '../types';

export const hadithQuotes: Omit<Quote, 'id'>[] = [
    { number: 1, text: "The believer's shade on the Day of Resurrection will be their charity.", source: "Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 2, text: "Charity does not decrease wealth.", source: "Sahih Muslim 2588", category: "Hadith", categoryTypeNumber: 2 },
    { number: 3, text: "Protect yourself from hellfire even by giving a piece of a date as charity.", source: "Sahih al-Bukhari 1417", category: "Hadith", categoryTypeNumber: 2 },
    { number: 4, text: "When a man dies, his deeds come to an end except for three things: Sadaqah Jariyah (ceaseless charity); a knowledge which is beneficial, or a virtuous descendant who prays for him.", source: "Sahih Muslim 1631", category: "Hadith", categoryTypeNumber: 2 },
    { number: 5, text: "The upper hand is better than the lower hand. The upper hand is the one that gives, and the lower hand is the one that takes.", source: "Sahih al-Bukhari 1429", category: "Hadith", categoryTypeNumber: 2 },
    { number: 6, text: "Every act of goodness is charity.", source: "Sahih Muslim 1005", category: "Hadith", categoryTypeNumber: 2 },
    { number: 7, text: "Give charity without delay, for it stands in the way of calamity.", source: "Al-Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 8, text: "The best charity is that which is practiced by a wealthy person. And start giving first to your dependents.", source: "Sahih al-Bukhari 1426", category: "Hadith", categoryTypeNumber: 2 },
    { number: 9, text: "Allah is in the aid of His servant as long as the servant is in the aid of his brother.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 10, text: "Wealth is not diminished by charity. And a forgiving servant is not increased by Allah except in honor. And no one humbles himself for the sake of Allah but that Allah will raise his status.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 11, text: "A charity is due for every joint in each person on every day the sun comes up.", source: "Sahih al-Bukhari 2989", category: "Hadith", categoryTypeNumber: 2 },
    { number: 12, text: "The best of people are those who are most beneficial to people.", source: "Prophet Muhammad (ﷺ), Musnad Ahmed", category: "Hadith", categoryTypeNumber: 2 },
    { number: 13, text: "Charity extinguishes sins just as water extinguishes fire.", source: "Al-Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 14, text: "Whoever relieves a believer’s distress of the distressful aspects of this world, Allah will rescue him from a difficulty of the difficulties of the Hereafter.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 15, text: "The best charity is to satisfy a hungry person.", source: "Prophet Muhammad (ﷺ), Bayhaqi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 16, text: "A man giving a dirham in his lifetime is better than giving one hundred dirhams when he is dying.", source: "Sunan Abi Dawud", category: "Hadith", categoryTypeNumber: 2 },
    { number: 17, text: "The best charity is giving water to drink.", source: "Ahmad", category: "Hadith", categoryTypeNumber: 2 },
    { number: 18, text: "Smiling in the face of your brother is charity.", source: "Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 19, text: "Every Muslim has to give in charity. The people asked, 'O Allah's Messenger! If someone has nothing to give, what will he do?' He said, 'He should work with his hands and benefit himself and also give in charity (from what he earns).'", source: "Sahih al-Bukhari 1445", category: "Hadith", categoryTypeNumber: 2 },
    { number: 20, text: "The most beloved deed to Allah is the most regular and constant even if it were little.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 21, text: "Visit the sick, feed the hungry, and free the captive.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 22, text: "There is a reward for kindness to every living thing.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 23, text: "He is not a believer who eats his fill while his neighbor beside him is hungry.", source: "Bayhaqi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 24, text: "Allah said, 'O son of Adam! Spend, and I shall spend on you.'", source: "Sahih al-Bukhari 5352", category: "Hadith", categoryTypeNumber: 2 },
    { number: 25, text: "Let he who has a spare mount lend it to him who has none, and let he who has a surplus of provisions give it to him who has none.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 26, text: "There is no envy except in two cases: a man whom Allah has given wealth and he spends it righteously, and a man whom Allah has given wisdom and he judges and teaches with it.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 27, text: "A dirham of Riba (interest) which a man receives knowingly is worse than committing adultery thirty-six times.", source: "Mishkat al-Masabih", category: "Hadith", categoryTypeNumber: 2 },
    { number: 28, text: "Indeed, the truthful, trustworthy merchant is with the Prophets, the truthful, and the martyrs.", source: "Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 29, text: "The one who looks after a widow or a poor person is like a Mujahid (warrior) who fights for Allah's cause, or like him who performs prayers all the night and fasts all the day.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 30, text: "To give up a dirham of Riba is more beloved to me than to give 100,000 dirhams in charity.", source: "Imam Ahmad", category: "Hadith", categoryTypeNumber: 2 },
    { number: 31, text: "Verily, the believers are like a structure, each part strengthening the other.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 32, text: "The example of the believers in their affection, mercy, and compassion for each other is that of a body. When any limb aches, the whole body reacts with sleeplessness and fever.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 33, text: "Whoever does not show mercy to our young ones, or acknowledge the rights of our elders, is not one of us.", source: "Ahmad", category: "Hadith", categoryTypeNumber: 2 },
    { number: 34, text: "Allah will not be merciful to those who are not merciful to mankind.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 35, text: "If anyone fulfills his brother's needs, Allah will fulfill his needs; if one relieves a Muslim of his troubles, Allah will relieve his troubles on the Day of Resurrection.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 36, text: "Pay the worker his wages before his sweat dries.", source: "Ibn Majah", category: "Hadith", categoryTypeNumber: 2 },
    { number: 37, text: "A Muslim is the brother of a Muslim. He does not wrong him, forsake him, or despise him. It is enough evil for a man to despise his Muslim brother.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 38, text: "Whoever among you sees an evil action, let him change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart—and that is the weakest of faith.", source: "Sahih Muslim", category: "Hadith", categoryTypeNumber: 2 },
    { number: 39, text: "The one who is proficient in the recitation of the Qur'an will be with the honorable and obedient scribes (angels) and he who recites the Qur'an and finds it difficult to recite, doing his best to recite it in the best way possible, will have a double reward.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 40, text: "A kind word is a form of charity.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 41, text: "A man's spending on his family is a deed of charity.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 42, text: "The Prophet (ﷺ) was the most generous of all the people, and he used to be more so in the month of Ramadan.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 43, text: "If a person gives in charity the equivalent of a date from pure earnings – for Allah accepts only that which is pure – Allah accepts it with His Right Hand and fosters it for him, as one of you fosters his foal, until it becomes like a mountain.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 44, text: "Do not withhold your money, otherwise Allah will withhold His blessings from you.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 45, text: "There is no person who has a camel or a cow or a sheep, and does not pay its Zakat, but it will be brought on the Day of Resurrection, larger and fatter than it was, and it will butt him with its horns and trample him with its hooves.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 46, text: "I and the person who looks after an orphan and provides for him, will be in Paradise like this,\" (putting his index and middle fingers together).", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 47, text: "Avoid the seven great destructive sins: associating partners with Allah, magic, killing the soul which Allah has forbidden except for a just cause, consuming interest, consuming an orphan's wealth, fleeing from the battlefield, and slandering chaste, innocent, believing women.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 48, text: "There is no disease that Allah has created, except that He also has created its treatment.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 },
    { number: 49, text: "The best of you are those who are best to their families, and I am the best of you to my family.", source: "Tirmidhi", category: "Hadith", categoryTypeNumber: 2 },
    { number: 50, text: "Whoever builds a mosque for Allah, Allah will build for him a house in Paradise.", source: "Sahih al-Bukhari", category: "Hadith", categoryTypeNumber: 2 }
];
