
/**
 * @fileOverview A collection of quotes from Islamic scholars related to charity.
 */
import type { Quote } from '../types';

export const scholarQuotes: Omit<Quote, 'id'>[] = [
    { number: 1, text: "A man's true wealth is the good he does in this world.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 2, text: "Do not feel ashamed if the amount of charity is small, because to refuse the needy is an act of greater shame.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 3, text: "The wealth of a miser is as useless as a pebble.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 4, text: "Knowledge without action is arrogance.", source: "Imam Al-Ghazali", category: "Scholar", categoryTypeNumber: 3 },
    { number: 5, text: "Do not withhold your money from the poor, for if you do, Allah will withhold His blessings from you.", source: "Ibn Qayyim Al-Jawziyya", category: "Scholar", categoryTypeNumber: 3 },
    { number: 6, text: "If you are unable to do a good deed, then at least do not do a bad one.", source: "Abu Bakr (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 7, text: "Sincerity is to forget the creation by constantly looking at the Creator.", source: "Ibn Qayyim Al-Jawziyya", category: "Scholar", categoryTypeNumber: 3 },
    { number: 8, text: "The best richness is the richness of the soul.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 9, text: "Seek knowledge from the cradle to the grave.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 10, text: "Generosity is not in giving me that which I need more than you, but it is in giving me that which you need more than I.", source: "Khalil Gibran", category: "Scholar", categoryTypeNumber: 3 },
    { number: 11, text: "Patience is a pillar of faith.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 12, text: "Forgive people so that perhaps Allah may forgive you.", source: "Uthman ibn Affan (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 13, text: "The most beloved of deeds to Allah are the most consistent of them, even if they are few.", source: "Imam Nawawi's 40 Hadith", category: "Scholar", categoryTypeNumber: 3 },
    { number: 14, text: "The life of this world is nothing but a provision, and the Hereafter is the final destination.", source: "Hasan al-Basri", category: "Scholar", categoryTypeNumber: 3 },
    { number: 15, text: "Whoever is not grateful to people is not grateful to Allah.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 16, text: "Give the gift of knowledge, it is the highest of all charities.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 17, text: "Do not look down upon any good deed, even if it be only meeting your brother with a cheerful face.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 18, text: "The best way to find yourself is to lose yourself in the service of others.", source: "Mahatma Gandhi", category: "Scholar", categoryTypeNumber: 3 },
    { number: 19, text: "Your wealth is not yours, but it is a trust from Allah, so spend it in His way.", source: "Uthman ibn Affan (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 20, text: "The best among you are those who have the best manners and character.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 21, text: "The greatest jihad is to battle your own soul, to fight the evil within yourself.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 22, text: "The world is a prison for the believer and a paradise for the disbeliever.", source: "Sahih Muslim", category: "Scholar", categoryTypeNumber: 3 },
    { number: 23, text: "Let not your tongue mention the shame of another, for you yourself are covered in shame and the people are all tongues.", source: "Imam Shafi'i", category: "Scholar", categoryTypeNumber: 3 },
    { number: 24, text: "He who has a thousand friends has not a friend to spare, and he who has one enemy will meet him everywhere.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 25, text: "To be busy with the unbecoming is the most unbecoming.", source: "Abu Bakr (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 26, text: "The less of the world, the freer you are.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 27, text: "A little of the world is a lot, and a lot of it is not enough.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 28, text: "When you see a person who has been given more than you in money and beauty, then look to those who have been given less.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 29, text: "The tears that are shed for fear of Allah are a proof of the sincerity of your faith.", source: "Imam Al-Ghazali", category: "Scholar", categoryTypeNumber: 3 },
    { number: 30, text: "Verily, the hearts of the children of Adam are between two fingers of the Most Merciful, and He turns them as He wills.", source: "Sahih Muslim", category: "Scholar", categoryTypeNumber: 3 },
    { number: 31, text: "The foundation of all good is the knowledge of God.", source: "Imam Al-Ghazali", category: "Scholar", categoryTypeNumber: 3 },
    { number: 32, text: "The world is a bridge, so pass over it, but do not build your dwellings on it.", source: "Jesus (Isa), son of Maryam (as)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 33, text: "Be in this world as if you were a stranger or a traveler.", source: "Sahih al-Bukhari", category: "Scholar", categoryTypeNumber: 3 },
    { number: 34, text: "The biggest of sins is to tell a lie.", source: "Abu Bakr (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 35, text: "The most complete of the believers in faith is the one with the best of character.", source: "Tirmidhi", category: "Scholar", categoryTypeNumber: 3 },
    { number: 36, text: "He who has no guts has no religion.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 37, text: "The key to all good is to be content with Allah.", source: "Ibn Qayyim Al-Jawziyya", category: "Scholar", categoryTypeNumber: 3 },
    { number: 38, text: "The more you give, the more you will have.", source: "Lao Tzu (adapted)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 39, text: "Riches are not from an abundance of worldly goods, but from a contented mind.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 40, text: "Do for this world as if you will live forever, and for the next world as if you will die tomorrow.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 41, text: "The people who are most deserving of my intercession on the Day of Resurrection are those who send the most prayers upon me.", source: "Tirmidhi", category: "Scholar", categoryTypeNumber: 3 },
    { number: 42, text: "There is no deed that is better than to be good to your parents.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 43, text: "The strong man is not the good wrestler; the strong man is only the one who controls himself when he is angry.", source: "Sahih al-Bukhari", category: "Scholar", categoryTypeNumber: 3 },
    { number: 44, text: "The cleverest of you is the one who is most mindful of death.", source: "Umar ibn al-Khattab (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 45, text: "The world is a marketplace, where the night and day are your capital, and your deeds are your business. Your profit is Paradise, and your loss is Hellfire.", source: "Hasan al-Basri", category: "Scholar", categoryTypeNumber: 3 },
    { number: 46, text: "A person's true character is known in three situations: in travel, in anger, and in financial dealings.", source: "Imam Jafar as-Sadiq", category: "Scholar", categoryTypeNumber: 3 },
    { number: 47, text: "The tongue is a small thing, but it can kill a man.", source: "Imam Ali (RA)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 48, text: "The one who does not thank for a little will not thank for a lot.", source: "Prophet Muhammad (ﷺ)", category: "Scholar", categoryTypeNumber: 3 },
    { number: 49, text: "The most hated of permissible things to Allah is divorce.", source: "Sunan Abi Dawud", category: "Scholar", categoryTypeNumber: 3 },
    { number: 50, text: "To seek knowledge is an obligation on every Muslim.", source: "Ibn Majah", category: "Scholar", categoryTypeNumber: 3 }
];
